[update] Add banner to let users know OCR is running
tyzesc/Portal-OCR pull request #5
Opened 2020-07-11 14:01 UTC by racterub

新 commit (squashed commits)

2020-07-11 14:02 UTC, racterub commented
Ref: PR#4

2020-07-11 14:27 UTC, tyzesc commented on YZU-Portal-OCR-Extension/content.js
> +            document.querySelector("#imgRCode").parentNode.innerHTML = "正在自動辨識";
咦 這裡好像多改到了 這裡是用 parentElement
```javascript
document.querySelector('#imgRCode').parentElement.innerHTML = "正在自動辨識";
```

2020-07-11 14:29 UTC, tyzesc requested changes
只剩這個咯～ 我先送審 Google 上架後 merge

2020-07-12 01:36 UTC, racterub commented
修好摟！

2020-07-12 06:04 UTC, merged